language: node_js
node_js:
  - 8
  - 10
git:
  depth: 5
cache:
  directories:
    - node_modules
script: npm t && npm run docs:build
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now dist --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now dist --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
